In [32]:
import random
import numpy as np
n_points=20
random.seed(42)
grade = [random.random() for ii in range(0,n_points)]
#     bumpy = [random.random() for ii in range(0,n_points)]
#     error = [random.random() for ii in range(0,n_points)]
#     y = [round(grade[ii]*bumpy[ii]+0.3+0.1*error[ii]) for ii in range(0,n_points)]
#     for ii in range(0, len(y)):
#         if grade[ii]>0.8 or bumpy[ii]>0.8:
#             y[ii] = 1.0
print grade
print len(grade)
grade_np = random.random()
print grade_np
print random.randint(1,20)
print np.arange(1,20)
print [random.random() for j in range(0,5)]
print [random.randint(1,3) for k in range(0,9)]  # 9 random integer(from 1 to 3) generator

[0.6394267984578837, 0.025010755222666936, 0.27502931836911926, 0.22321073814882275, 0.7364712141640124, 0.6766994874229113, 0.8921795677048454, 0.08693883262941615, 0.4219218196852704, 0.029797219438070344, 0.21863797480360336, 0.5053552881033624, 0.026535969683863625, 0.1988376506866485, 0.6498844377795232, 0.5449414806032167, 0.2204406220406967, 0.5892656838759087, 0.8094304566778266, 0.006498759678061017]
20
0.805819251833
14
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.3402505165179919, 0.15547949981178155, 0.9572130722067812, 0.33659454511262676, 0.09274584338014791]
[1, 3, 2, 3, 3, 2, 3, 2, 2]


In [37]:
# train data & test data split
from sklearn.cross_validation import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
print X
print "y:",y
list(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print "X_train :\n",X_train
print "y_train :\n",y_train
print "X_test :\n",X_test
print "y_test :\n",y_test

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y: [0, 1, 2, 3, 4]
X_train :
[[4 5]
 [0 1]
 [6 7]]
y_train :
[2, 0, 3]
X_test :
[[2 3]
 [8 9]]
y_test :
[1, 4]
