In [4]:
# %%writefile ages_net_worths.py

import numpy
import random

def ageNetWorthData():

    random.seed(42)
    numpy.random.seed(42)

    ages = []
    for ii in range(100):
        ages.append( random.randint(20,65) )  #random.randint(start,end)
    net_worths = [ii * 6.25 + numpy.random.normal(scale=40.) for ii in ages]
### need massage list into a 2d numpy array to get it to work in LinearRegression
    ages       = numpy.reshape( numpy.array(ages), (len(ages), 1))
    net_worths = numpy.reshape( numpy.array(net_worths), (len(net_worths), 1))

    from sklearn.cross_validation import train_test_split
#train_test_split(arrays, options)Split arrays or matrices into random train and test subsets
    
    ages_train, ages_test, net_worths_train, net_worths_test = train_test_split(ages, net_worths)

    return ages_train, ages_test, net_worths_train, net_worths_test

#### numpy.random.normal(loc=0.0, scale=1.0, size=None): Draw random samples from a normal (Gaussian) distribution.
* loc :Mean (“centre”) of the distribution.
* scale :Standard deviation (spread or “width”) of the distribution.
* size : Output shape. If the given shape is, e.g., (m, n, k), then m n k samples are drawn. Default is None, in which case a single value is returned.

In [7]:
#test
import numpy as np
a = np.arange(6).reshape((3, 2))
print a; "*"*40
print np.reshape(a, (2, 3))

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [8]:
#test 
import numpy 
import random
ages=[]
for ii in range(100):
    ages.append(random.randint(20,65))
net_worths = [il2* 6.25 + numpy.random.normal(scale=40.) for il2 in ages]
print ages
print "*net_worths:\n",net_worths
print len(ages)
ages_reshape = numpy.reshape(numpy.array(ages), (len(ages),1))  #reshapte to 2d array(100*1)
print ages_reshape
    

[57, 50, 50, 35, 60, 30, 37, 50, 27, 44, 40, 48, 31, 42, 43, 30, 43, 60, 54, 64, 34, 64, 46, 48, 59, 55, 50, 48, 30, 52, 23, 32, 41, 23, 22, 30, 50, 48, 56, 46, 64, 55, 51, 64, 34, 20, 31, 44, 40, 32, 58, 48, 34, 23, 51, 31, 25, 36, 32, 28, 62, 34, 41, 23, 61, 34, 30, 53, 61, 54, 39, 36, 27, 22, 42, 53, 64, 42, 47, 24, 55, 22, 42, 52, 25, 61, 46, 28, 22, 20, 52, 58, 24, 54, 50, 39, 43, 30, 64, 50]
*net_worths:
[330.87473270328985, 321.4899641118624, 256.66113793608844, 199.83152296817642, 382.1194594735003, 175.9518335285877, 202.81348144096316, 312.55338282495364, 180.5021518250737, 247.27122240316913, 347.87235975747603, 351.7080372135105, 182.6012550125497, 313.05484161394867, 262.5251752939188, 198.49867340995644, 255.84390139433606, 340.1898586939684, 356.1517460717862, 361.8380916647256, 217.98778317724518, 396.3555493544201, 269.04834989911086, 305.7574930137315, 400.7401591508659, 376.5352674545512, 324.3887108521177, 274.18864528642155, 169.68740941102934, 293.5834554645861, 5

In [9]:
#test: train_test_split(X, y, test_size=0.33, random_state=42)
>>> import numpy as np
>>> from sklearn.cross_validation import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
>>> list(y)

[0, 1, 2, 3, 4]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
print  "X_train \n", X_train
print "X_test \n",X_test
print "y_train\n",y_train
print "y_test\n",y_test

X_train 
[[4 5]
 [0 1]
 [6 7]]
X_test 
[[2 3]
 [8 9]]
y_train
[2, 0, 3]
y_test
[1, 4]


In [18]:
# %%writefile regressionQuiz.py

import numpy
import matplotlib.pyplot as plt

from ages_net_worths import ageNetWorthData

ages_train, ages_test, net_worths_train, net_worths_test = ageNetWorthData()



from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(ages_train, net_worths_train)

### get Katie's net worth (she's 27)
### sklearn predictions are returned in an array,
### so you'll want to do something like net_worth = predict([27])[0]
### (not exact syntax, the point is that [0] at the end)
km_net_worth = reg.predict([27])[0] ### fill in the line of code to get the right value

### get the slope
### again, you'll get a 2-D array, so stick the [0][0] at the end
slope = reg.coef_ ### fill in the line of code to get the right value

### get the intercept
### here you get a 1-D array, so stick [0] on the end to access
### the info we want
intercept = reg.intercept_ ### fill in the line of code to get the right value


### get the score on test data
test_score = reg.score(ages_test,net_worths_test) ### fill in the line of code to get the right value


### get the score on the training data
training_score = reg.score(ages_train,net_worths_train) ### fill in the line of code to get the right value



def submitFit():
    return {"networth":km_net_worth,
            "slope":slope,
            "intercept":intercept,
            "stats on test":test_score,
            "stats on training": training_score}

In [19]:
submitFit()

{'intercept': array([-14.35378133]),
 'networth': array([ 160.43205651]),
 'slope': array([[ 6.47354955]]),
 'stats on test': 0.81236573057499983,
 'stats on training': 0.87458823582171819}