In [23]:
#%%writefile ages_net_worths.py

import numpy
import numpy as np
import random
random.seed(42)
numpy.random.seed(42)

ages = []
for ii in range(100):
    ages.append( random.randint(20,65) )  #random.randint(start,end)
net_worths = [ii * 6.25 + numpy.random.normal(scale=40.) for ii in ages]
print "ages:\n",ages
print "len(ages) :",len(ages)
### need massage list into a 2d numpy array to get it to work in LinearRegression
ages       = numpy.reshape( numpy.array(ages), (len(ages), 1)) #np.reshape(a,b,c) as for array a, convert to b*c metrics 
print "after reshape :\n",ages
#np.reshape(a,b,c) : af for array "a" , reshape to row: b * column: c 
net_worths = numpy.reshape( numpy.array(net_worths), (len(net_worths), 1))  

from sklearn.cross_validation import train_test_split
ages_train, ages_test, net_worths_train, net_worths_test = train_test_split(ages, net_worths)

#ages_train, ages_test, net_worths_train, net_worths_test
#print net_worths
#

print np.random.normal(scale=40.)
print 

ages:
[49, 21, 32, 30, 53, 51, 61, 23, 39, 21, 30, 43, 21, 29, 49, 45, 30, 47, 57, 20, 57, 52, 35, 27, 64, 35, 24, 24, 58, 47, 57, 53, 44, 64, 37, 45, 58, 48, 59, 46, 52, 22, 30, 33, 23, 30, 24, 32, 49, 36, 37, 29, 32, 63, 49, 48, 27, 53, 27, 37, 65, 49, 45, 51, 58, 55, 30, 21, 34, 32, 29, 63, 60, 34, 50, 38, 62, 41, 32, 31, 45, 32, 46, 61, 38, 30, 65, 43, 24, 22, 25, 48, 56, 39, 22, 37, 65, 44, 64, 59]
len(ages) : 100
after reshape :
[[49]
 [21]
 [32]
 [30]
 [53]
 [51]
 [61]
 [23]
 [39]
 [21]
 [30]
 [43]
 [21]
 [29]
 [49]
 [45]
 [30]
 [47]
 [57]
 [20]
 [57]
 [52]
 [35]
 [27]
 [64]
 [35]
 [24]
 [24]
 [58]
 [47]
 [57]
 [53]
 [44]
 [64]
 [37]
 [45]
 [58]
 [48]
 [59]
 [46]
 [52]
 [22]
 [30]
 [33]
 [23]
 [30]
 [24]
 [32]
 [49]
 [36]
 [37]
 [29]
 [32]
 [63]
 [49]
 [48]
 [27]
 [53]
 [27]
 [37]
 [65]
 [49]
 [45]
 [51]
 [58]
 [55]
 [30]
 [21]
 [34]
 [32]
 [29]
 [63]
 [60]
 [34]
 [50]
 [38]
 [62]
 [41]
 [32]
 [31]
 [45]
 [32]
 [46]
 [61]
 [38]
 [30]
 [65]
 [43]
 [24]
 [22]
 [25]
 [48]
 [56]
 [3

#### numpy.random.normal(loc=0.0, scale=1.0, size=None):  Draw random samples from a normal (Gaussian) distribution.
* loc :Mean (“centre”) of the distribution.
* scale :Standard deviation (spread or “width”) of the distribution.
* size : Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

In [11]:
a = np.zeros((10, 2))
print a

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [12]:
b = a.T
print b

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [13]:
# Taking a view makes it possible to modify the shape without modifying
# the initial object.
c = b.view()
print c

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [17]:
c.shape = (20)

AttributeError: incompatible shape for a non-contiguous array

In [18]:
print np.arange(6)

[0 1 2 3 4 5]


In [16]:
 a = np.arange(6).reshape((3, 2))
print a

[[0 1]
 [2 3]
 [4 5]]
